# ConfigMap for fhir-sandbox-dev
#
# k8s documentation:
# - https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-a-configmap
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: fhir-sandbox-dev
data:
  EXTRA_JAVA_OPTS: -XX:MaxRAMPercentage=75.0
  SERVER_SERVLET_CONTEXTPATH: /fhir-sandbox
  TZ: America/Los_Angeles
  ENVIRONMENT_BANNER_ENABLED: "true"
  ENVIRONMENT_BANNER_TEXT: dev
  SPRING_MAIL_HOST: mailpit-dev
  OCTRI_AUTHENTICATION_BASEURL: https://octridev.ohsu.edu
