spring.config.import=optional:dev.properties

spring.mustache.prefix=classpath:/mustache-templates/
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.request-context-attribute=req

app.name=@project.artifactId@
app.version=@project.version@
app.displayName=OCTRI FHIR Sandbox

server.servlet.context-path=/fhir-sandbox
server.forward-headers-strategy=native
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

logging.level.org.hibernate=ERROR
logging.level.org.springframework.security=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/fhir_sandbox?serverTimezone=America/Los_Angeles
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=fhir_sandbox
spring.datasource.password=fhir_sandbox

spring.jpa.database-platform=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.data.rest.base-path=api

# Fixture data
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/fixtures/translations.sql
logging.level.org.springframework.jdbc.datasource.init=INFO

# Metrics
management.endpoint.metrics.access=read-only
management.endpoints.web.exposure.include=health
management.endpoint.prometheus.access=read-only
management.prometheus.metrics.export.enabled=true

# Disable high-cardinality http_server_requests_seconds* metrics by default.
management.observations.enable.spring.security=false
management.observations.enable.http.server.requests=false

# Swallow the constraint violation exception logged by this class since the app handles it
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=off

# Translations
octri.i18n.template-key=i18n
octri.i18n.default-locale=en_US
# octri.i18n.supported-locales=en_US,fr,es
octri.i18n.supported-locales=en_US
octri.i18n.content-editing-enabled=false

# Caching
# By default, cache data for 10 minutes after the last access and cap each cache at 500 items.
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s

# Uncomment to completely disable translation cache
# spring.cache.type=none

# Banner that identifies the application environment
environment-banner.enabled=false
environment-banner.text=

# Authentication Library Properties

ldap.context-source.url=ldaps://ldap.ohsu.edu:636
ldap.context-source.user-dn=
ldap.context-source.password=
ldap.context-source.search-base=ou=User Accounts,dc=ohsum01,dc=ohsu,dc=edu
ldap.context-source.search-filter=(sAMAccountName={0})
ldap.context-source.organization=OHSU
ldap.context-source.email-domain=ohsu.edu

octri.authentication.enable-ldap=true
octri.authentication.enable-table-based=false
octri.authentication.saml.enabled=false
octri.authentication.password-token-valid-for=3d

octri.authentication.role-style=single

octri.authentication.routes.default-login-success-url=/
octri.authentication.routes.logout-success-url=/

octri.messaging.email.default-sender-address=criapps@ohsu.edu
octri.authentication.account-message-email=criapps@ohsu.edu
octri.messaging.email-delivery-strategy=LOG

spring.mail.default-encoding=UTF-8
spring.mail.host=smtpout.ohsu.edu
spring.mail.port=25
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.username=octrihlp@ohsu.edu
spring.mail.password=secret
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# FHIR server
octri.fhir.base-url=http://localhost:8000/fhir
octri.fhir.default-partition=DEFAULT
