---
apiVersion: v1
kind: Service
metadata:
  name: fhir-sandbox-stage
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fhir-sandbox-stage
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: fhir-sandbox-stage
spec:
  hostname: octristage.ohsu.edu
  prefix: /fhir-sandbox
  rewrite: /fhir-sandbox
  service: fhir-sandbox-stage
